version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/ohsool
hooks:   
  ApplicationStop: 
    - location: scripts/application_stop.sh
      timeout: 500
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 500
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 500
      runas: ec2-user
  

