version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo $SECRET-KEY-SCRIPT
  pre_build:
    commands:
      - npm install
      - echo npm installed
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - "**/*"

