version: 0.2

env:
  variables:
    NODE_ENV: "test"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
     - npm install -g jest
     - npm install -g supertest
  pre_build:
    commands:
      - npm install
      - echo npm installed
  build:
    commands:
      - echo begin test
      - npm test
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - "**/*"
