version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - export NODE_ENV=test
  pre_build:
    commands:
      - npm install
      - echo npm installed
  build:
    commands:
      - echo begin test
      - npm test
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - "**/*"
