version: 0.2
env:
  parameter-store:
    SECRET-KEY-SCRIPT: "/ohsool/ssl/secretApi"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo $SECRET-KEY-SCRIPT
  pre_build:
    commands:
      # Secretkey 파일 생성
      - echo $CODEBUILD_SRC_DIR
      - file="$CODEBUILD_SRC_DIR/ssl/secretAPI.ts"
      - mkdir ssl
      - touch $file
      - echo "import crypto from "crypto"; export const secretAPIkey = ( ) => { const time = new Date();" > $file 
      - echo "let key = String(time.getDate()) + String(time.getHours()) + String(time.getUTCFullYear()) + String(time.getUTCHours());" > $file
      - echo "key = crypto.createHmac('sha256', key).digest('base64'); key = key.replace(/[^a-zA-Z ]/g, "") return key; };" > $file
      # test mode로 변경
      - export NODE_ENV=test
      - echo node -v
      - npm install
      - echo npm installed
  build:
    commands:
      - echo begin test
      - npm test
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - "**/*"
  base-directory: "**/*"

