version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - export NODE_ENV=test
      - echo "${NODE_ENV} mode is on"
  pre_build:
    commands:
      - npm install
      - echo npm installed
  build:
    commands:
      - echo begin test
      - npm test
      - echo end test
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - "**/*"
